### ISSUE TITLE
Massive expansion of ruleset size due to <if_group>windows</if_group>

### ISSUE THREAD

**Issue by branchnetconsulting** [SanWieb/sigWah#1]
Hi, 

I really like your work on this and have already started putting it to fruitful use.  I did find that when I bolt these rules onto the stock Wazuh ruleset, that the internal rule count sky rockets to over 200,000 rules, about 50 times bigger than normal.  This pushes Wazuh's memory requirements for analysisd (which loads the ruleset) up to over 2GB and makes ruleset load time go from very quick to around 10 seconds, delaying ossec-logtest and wazuh-manager service restarts.  Other than the memory demands and the slow ruleset loading, it seems to be working fine.  I was discussing this with Wazuh's head developer this morning and he discourages heavy use of <if_group> because 

> <if_group> is a shortcut to create N rules with <if_sid> for each existing rule belonging that group.

This issue is amplified with **<if_group>windows</if_group>** specifically because there are so very many rules in the **windows** group.  It would be ideal if these Sigma-related Wazuh rules could be hung off of the specific Wazuh parent rules relevant to them using the **<if_sid>** construct instead of **<if_group>** but that may make automatic generation of Wazuh rules based off of the Sigma ruleset much more difficult.  Still, it would give vastly more than an order of magnitude analysisd memory reduction and Wazuh ruleset load speed.

What do you think?
Kevin

**Comment by SanWieb** [comment]
Hi Keven,

First of all, sorry for the late reply. 
Glad your finding the project useful and thanks for noticing this problem! I do not think that the use of the <group> parameter in itself is the problem.  Wazuh uses also `<if_group>sysmon_event1</if_group>` instead of `<if_sid>18100</if_sid>`, shown [here](https://github.com/wazuh/wazuh-ruleset/blob/master/rules/0330-sysmon_rules.xml)[1]. But the use of very large, not specific, groups which indeed cause this high memory usage.

I think when you create more groups for the higher eventID's (15+), just like [1]. Then replace all common windows tags with the specific event group it would be a lot better, so for example:

```
<if_group>windows</if_group>
<field name="win.system.EventID">^17$</field>
```
will become:
```
<if_group>sysmon_event17</if_group>
```

It is also possible to use the `<if_sid>` of the `<group>sysmon_event17</group>`

I stopped maintaining this project, but feel free to make a pull request. For my use, the streaming method of Wazuh is not practical. The rule syntax limits the rule complexity. The elastic SIEM with agent is for me the perfect solution. It uses KQL query, so it has (almost) no limitations.
